// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/category-management/category": {
    params: {};
  };
  "/category-management/sub-category": {
    params: {};
  };
  "/service-management/services-list": {
    params: {};
  };
  "/service-management/add-service": {
    params: {};
  };
  "/service-management/edit-service/:id": {
    params: {
      "id": string;
    };
  };
  "/booking-management/booking-list": {
    params: {};
  };
  "/providers-management/active-providers": {
    params: {};
  };
  "/providers-management/pending-providers": {
    params: {};
  };
  "/providers-management/provider-services": {
    params: {};
  };
  "/providers-management/provider-earnings": {
    params: {};
  };
  "/providers-management/providers-performance": {
    params: {};
  };
  "/payout/payout-history": {
    params: {};
  };
  "/payout/new-payout": {
    params: {};
  };
  "/customer-management/customer-list": {
    params: {};
  };
  "/customer-management/customer-ratings": {
    params: {};
  };
  "/customer-management/payments-list": {
    params: {};
  };
  "/system-users/users-list": {
    params: {};
  };
  "/system-users/new-user": {
    params: {};
  };
  "/points-management/points-configuration": {
    params: {};
  };
  "/points-management/points-overview": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/category-management/category" | "/category-management/sub-category" | "/service-management/services-list" | "/service-management/add-service" | "/service-management/edit-service/:id" | "/booking-management/booking-list" | "/providers-management/active-providers" | "/providers-management/pending-providers" | "/providers-management/provider-services" | "/providers-management/provider-earnings" | "/providers-management/providers-performance" | "/payout/payout-history" | "/payout/new-payout" | "/customer-management/customer-list" | "/customer-management/customer-ratings" | "/customer-management/payments-list" | "/system-users/users-list" | "/system-users/new-user" | "/points-management/points-configuration" | "/points-management/points-overview";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./layouts/AuthGuard.tsx": {
    id: "layouts/AuthGuard";
    page: "/" | "/category-management/category" | "/category-management/sub-category" | "/service-management/services-list" | "/service-management/add-service" | "/service-management/edit-service/:id" | "/booking-management/booking-list" | "/providers-management/active-providers" | "/providers-management/pending-providers" | "/providers-management/provider-services" | "/providers-management/provider-earnings" | "/providers-management/providers-performance" | "/payout/payout-history" | "/payout/new-payout" | "/customer-management/customer-list" | "/customer-management/customer-ratings" | "/customer-management/payments-list" | "/system-users/users-list" | "/system-users/new-user" | "/points-management/points-configuration" | "/points-management/points-overview";
  };
  "./layouts/adminLayout.tsx": {
    id: "layouts/adminLayout";
    page: "/" | "/category-management/category" | "/category-management/sub-category" | "/service-management/services-list" | "/service-management/add-service" | "/service-management/edit-service/:id" | "/booking-management/booking-list" | "/providers-management/active-providers" | "/providers-management/pending-providers" | "/providers-management/provider-services" | "/providers-management/provider-earnings" | "/providers-management/providers-performance" | "/payout/payout-history" | "/payout/new-payout" | "/customer-management/customer-list" | "/customer-management/customer-ratings" | "/customer-management/payments-list" | "/system-users/users-list" | "/system-users/new-user" | "/points-management/points-configuration" | "/points-management/points-overview";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/category.tsx": {
    id: "routes/category";
    page: "/category-management/category";
  };
  "routes/subCategory.tsx": {
    id: "routes/subCategory";
    page: "/category-management/sub-category";
  };
  "routes/servicesList.tsx": {
    id: "routes/servicesList";
    page: "/service-management/services-list";
  };
  "routes/addService.tsx": {
    id: "routes/addService";
    page: "/service-management/add-service";
  };
  "routes/editService.tsx": {
    id: "routes/editService";
    page: "/service-management/edit-service/:id";
  };
  "routes/bookingList.tsx": {
    id: "routes/bookingList";
    page: "/booking-management/booking-list";
  };
  "routes/activeProviders.tsx": {
    id: "routes/activeProviders";
    page: "/providers-management/active-providers";
  };
  "routes/pendingProviders.tsx": {
    id: "routes/pendingProviders";
    page: "/providers-management/pending-providers";
  };
  "routes/providerServices.tsx": {
    id: "routes/providerServices";
    page: "/providers-management/provider-services";
  };
  "routes/providerEarnings.tsx": {
    id: "routes/providerEarnings";
    page: "/providers-management/provider-earnings";
  };
  "routes/providersPerformance.tsx": {
    id: "routes/providersPerformance";
    page: "/providers-management/providers-performance";
  };
  "routes/payoutHistory.tsx": {
    id: "routes/payoutHistory";
    page: "/payout/payout-history";
  };
  "routes/newPayout.tsx": {
    id: "routes/newPayout";
    page: "/payout/new-payout";
  };
  "routes/customerList.tsx": {
    id: "routes/customerList";
    page: "/customer-management/customer-list";
  };
  "routes/customerRatings.tsx": {
    id: "routes/customerRatings";
    page: "/customer-management/customer-ratings";
  };
  "routes/paymentsList.tsx": {
    id: "routes/paymentsList";
    page: "/customer-management/payments-list";
  };
  "routes/usersList.tsx": {
    id: "routes/usersList";
    page: "/system-users/users-list";
  };
  "routes/newUser.tsx": {
    id: "routes/newUser";
    page: "/system-users/new-user";
  };
  "routes/pointsConfiguration.tsx": {
    id: "routes/pointsConfiguration";
    page: "/points-management/points-configuration";
  };
  "routes/pointsOverview.tsx": {
    id: "routes/pointsOverview";
    page: "/points-management/points-overview";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "layouts/AuthGuard": typeof import("./app/./layouts/AuthGuard.tsx");
  "layouts/adminLayout": typeof import("./app/./layouts/adminLayout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/category": typeof import("./app/routes/category.tsx");
  "routes/subCategory": typeof import("./app/routes/subCategory.tsx");
  "routes/servicesList": typeof import("./app/routes/servicesList.tsx");
  "routes/addService": typeof import("./app/routes/addService.tsx");
  "routes/editService": typeof import("./app/routes/editService.tsx");
  "routes/bookingList": typeof import("./app/routes/bookingList.tsx");
  "routes/activeProviders": typeof import("./app/routes/activeProviders.tsx");
  "routes/pendingProviders": typeof import("./app/routes/pendingProviders.tsx");
  "routes/providerServices": typeof import("./app/routes/providerServices.tsx");
  "routes/providerEarnings": typeof import("./app/routes/providerEarnings.tsx");
  "routes/providersPerformance": typeof import("./app/routes/providersPerformance.tsx");
  "routes/payoutHistory": typeof import("./app/routes/payoutHistory.tsx");
  "routes/newPayout": typeof import("./app/routes/newPayout.tsx");
  "routes/customerList": typeof import("./app/routes/customerList.tsx");
  "routes/customerRatings": typeof import("./app/routes/customerRatings.tsx");
  "routes/paymentsList": typeof import("./app/routes/paymentsList.tsx");
  "routes/usersList": typeof import("./app/routes/usersList.tsx");
  "routes/newUser": typeof import("./app/routes/newUser.tsx");
  "routes/pointsConfiguration": typeof import("./app/routes/pointsConfiguration.tsx");
  "routes/pointsOverview": typeof import("./app/routes/pointsOverview.tsx");
};